name: Build-x86-64

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  Build:
    name: Build x86-64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: dnpl/iStoreOS_5.1
          path: iStoreOS_5.1
      - name: Cache
        uses: klever1988/cachewrtbuild@main
        with:
          ccache: 'true'
          prefix: ${{ github.workspace }}/iStoreOS_5.1
      - name: Delete Files
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Check Space
        run: |
          df -h
      - name: Update Package
        run: |
          sudo -E apt-get update -y
          sudo -E apt-get upgrade -y
      - name: Install Package
        run: |
          sudo -E apt-get install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig mkisofs -y

      - name: Update Feeds
        run: |
          cd ./iStoreOS_5.1
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Create Config
        run: |
          cd ./iStoreOS_5.1
          make defconfig
          cat ../x86-64.config > .config
          make defconfig
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config
          make defconfig
      - name: Check Space
        run: |
          df -h
      - name: Build
        run: |
          cd ./iStoreOS_5.1
          make -j$(($(nproc) + 1)) V=s || make -j1 V=s
      - name: Upload All
        uses: actions/upload-artifact@v3
        with:
          name: All Build Products
          path: ./iStoreOS_5.1/bin
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: Firmware
          path: ./iStoreOS_5.1/bin/targets/x86/64/openwrt-x86-64-generic-*
      - name: Generate Config
        run: |
          cd ./iStoreOS_5.1
          ./scripts/diffconfig.sh > seed.config
          cat seed.config > ../x86-64.config
      - name: Upload Config
        uses: actions/upload-artifact@v3
        with:
          name: Config
          path: |
            ./iStoreOS_5.1/.config
            ./iStoreOS_5.1/seed.config
      - name: Push Config
        uses: EndBug/add-and-commit@v9
        with:
          add: 'x86-64.config'
